runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: www/css

- url: /
  static_files: www/profile.html
  upload: www/profile.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)